import * as THREE from 'three';

const PI=Math.PI,DEG=PI/180,FREE=2,ACTIVE=[0,1,3,4,5,6],FIXED_Q3=30*DEG;
const COLORS=['#2474d2','#65a34a','#d18b00','#8b62a8','#008f95','#e00000','#666','#c25b9b'];
const LIMITS=[170,120,170,120,170,120,175].map(v=>v*DEG);
const REVISION=new URL(import.meta.url).searchParams.get('v')||'dev';
let viewerPromise,dataPromise,planningPromise;

export function initRedundantPlanningLecture(){
  const hosts=[...document.querySelectorAll('[data-l8-lab]')];if(!hosts.length)return;
  const done=new WeakSet(),ensure=host=>{if(done.has(host))return;done.add(host);createLab(host,host.dataset.l8Lab).catch(e=>fail(host,e));};
  const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)ensure(e.target);}),{threshold:.02,rootMargin:'120px'});hosts.forEach(h=>observer.observe(h));
  const sync=()=>{const n=Number(location.hash.match(/#slide-(\d+)/)?.[1]||1);document.querySelectorAll('#deck > .slide')[n-1]?.querySelectorAll('[data-l8-lab]').forEach(ensure);};sync();window.addEventListener('hashchange',sync);
}

async function createLab(host,mode){
  if(mode==='null-motion')return createNullLab(host);
  if(mode==='path-preview'||mode==='timing')return createPathPlot(host,mode);
  if(['enumerate','aspects','filter','play'].includes(mode))return createPlanningLab(host,mode);
  if(mode==='global-map')return createGlobalMap(host);
  throw new Error(`Unknown Lecture 08 lab: ${mode}`);
}

async function api(){if(!viewerPromise)viewerPromise=import(`./cuspidalityLecture.js?v=${REVISION}`);return viewerPromise;}
async function loadData(){
  if(!dataPromise)dataPromise=Promise.all([
    fetch(new URL('../../assets/data/null/iiwa7_IK_q3_030deg.csv',import.meta.url)).then(check).then(r=>r.text()),
    fetch(new URL('../../assets/data/path/kuka_iiwa7_rectangle_workspace_path_500_quaternion.csv',import.meta.url)).then(check).then(r=>r.text()),
    fetch(new URL('../../assets/data/path/kuka_iiwa7_rectangle_joint_path_500.csv',import.meta.url)).then(check).then(r=>r.text())
  ]).then(([seeds,poses,joints])=>({
    seeds:parseCsv(seeds,false),poses:parseCsv(poses,true).map(poseFromRow),reference:parseCsv(joints,true)
  }));
  return dataPromise;
}
function check(r){if(!r.ok)throw new Error(`Could not load ${r.url.split('/').at(-1)}.`);return r;}
function parseCsv(text,header){return text.trim().split(/\r?\n/).slice(header?1:0).map(line=>line.split(',').map(Number));}
function poseFromRow(r){const q=new THREE.Quaternion(r[4],r[5],r[6],r[3]).normalize(),T=new THREE.Matrix4().compose(new THREE.Vector3(...r.slice(0,3)),q,new THREE.Vector3(1,1,1));return{p:r.slice(0,3),q,T};}

async function createNullLab(host){
  host.className+=' l8-lab l8-null';host.innerHTML='<div class="l8-stage"><div class="hud">iiwa7_free_joints.urdf · fixed tool pose</div></div><aside><label class="l8-range"><span>redundancy coordinate q₃</span><input type="range" min="-150" max="150" step="2.5" value="30"><output>30.0°</output></label><div class="l8-readout">Loading the self-motion continuation…</div><canvas></canvas><p class="l8-status"></p></aside>';
  const stage=host.querySelector('.l8-stage'),input=host.querySelector('input'),out=host.querySelector('output'),readout=host.querySelector('.l8-readout'),status=host.querySelector('.l8-status'),canvas=host.querySelector('canvas'),{seeds}=await loadData(),{createModelViewer}=await api(),viewer=await createModelViewer(stage,'iiwa',{embedded:true,showEeFrame:true});
  const target=viewer.model.pose(seeds[0]),family=continueFamily(viewer.model,target,seeds[0],-150*DEG,150*DEG,2.5*DEG),pair=canvasKit(canvas,draw);input.min=(family[0].q[FREE]/DEG).toFixed(1);input.max=(family.at(-1).q[FREE]/DEG).toFixed(1);
  const set=()=>{const wanted=+input.value*DEG,node=family.reduce((a,b)=>Math.abs(b.q[FREE]-wanted)<Math.abs(a.q[FREE]-wanted)?b:a);viewer.update(node.q);out.textContent=`${(node.q[FREE]/DEG).toFixed(1)}°`;readout.textContent=`q = (${node.q.map(a=>(a/DEG).toFixed(1)+'°').join(', ')})\npose error = ${node.error.toExponential(2)}\nrank J = 6 · nullity = 1`;status.textContent=`The red/green/blue tool frame is stationary while six dependent joints compensate for q₃. ${family.length} feasible samples were continued from CSV solution 1.`;draw(node.q[FREE]);};
  input.addEventListener('input',set);function draw(current=+input.value*DEG){if(!pair.ready)return;const {ctx,w,h}=pair;clear(ctx,w,h);const pad=28,x=a=>pad+(a-family[0].q[FREE])/(family.at(-1).q[FREE]-family[0].q[FREE])*(w-2*pad),ys=[1,4,6];ctx.strokeStyle='#aaa';ctx.beginPath();ctx.moveTo(pad,h-24);ctx.lineTo(w-pad,h-24);ctx.stroke();ys.forEach((j,k)=>{ctx.strokeStyle=COLORS[k];ctx.lineWidth=2;ctx.beginPath();family.forEach((n,i)=>{const y=18+(k+.5)*(h-50)/3-(n.q[j]/PI)*(h-50)/8;i?ctx.lineTo(x(n.q[FREE]),y):ctx.moveTo(x(n.q[FREE]),y);});ctx.stroke();});ctx.fillStyle='#111';ctx.fillRect(x(current)-1,10,2,h-34);ctx.font='11px Arial';ctx.fillText('dependent joints q₂, q₅, q₇',pad,14);ctx.textAlign='center';ctx.fillText('q₃',w/2,h-6);ctx.textAlign='left';}set();
}

function continueFamily(model,target,seed,min,max,step){
  const center={q:seed.slice(),error:poseError(model.pose(seed),target).norm},left=[],right=[];let q=seed.slice();
  for(let v=seed[FREE]-step;v>=min-1e-9;v-=step){const s=solveFixed(model,target,q,v);if(!s)break;left.push(s);q=s.q;}
  q=seed.slice();for(let v=seed[FREE]+step;v<=max+1e-9;v+=step){const s=solveFixed(model,target,q,v);if(!s)break;right.push(s);q=s.q;}
  return[...left.reverse(),center,...right];
}

async function createPathPlot(host,mode){
  host.className+=' l8-lab l8-plot-lab';host.innerHTML='<canvas></canvas><aside><div class="l8-readout"></div><label class="l8-range"><span>normalized edge time τ</span><input type="range" min="0" max="1" step="0.005" value="0"><output>0.000</output></label><p class="l8-status"></p></aside>';
  const {poses}=await loadData(),canvas=host.querySelector('canvas'),input=host.querySelector('input'),out=host.querySelector('output'),readout=host.querySelector('.l8-readout'),status=host.querySelector('.l8-status'),pair=canvasKit(canvas,draw),edges=[0,150,250,399,499];
  const set=()=>{out.textContent=(+input.value).toFixed(3);draw();};input.addEventListener('input',set);
  function draw(){if(!pair.ready)return;const {ctx,w,h}=pair;clear(ctx,w,h);if(mode==='path-preview')drawSquare(ctx,w,h,poses,+input.value);else drawTiming(ctx,w,h,+input.value);const tau=+input.value,s=minJerk(tau),sd=30*tau*tau*(1-tau)*(1-tau),sdd=60*tau*(1-tau)*(1-2*tau);readout.textContent=mode==='path-preview'?`500 supplied pose samples\ncorner indices: ${edges.join(' · ')}\ncurrent edge progress s(τ) = ${s.toFixed(4)}`:`s = ${s.toFixed(4)}\nds/dτ = ${sd.toFixed(4)}\nd²s/dτ² = ${sdd.toFixed(4)}`;status.textContent=mode==='path-preview'?'The quaternion orientation is retained at every sample; the plot shows only the x–y projection.':'Every edge restarts the same scalar clock, so position, angular interpolation, and all IK paths share zero endpoint velocity and acceleration.';}set();
}
function drawSquare(ctx,w,h,poses,tau){const pad=38,xr=[.0,.6],yr=[-.45,.45],px=x=>pad+(x-xr[0])/(xr[1]-xr[0])*(w-2*pad),py=y=>pad+(yr[1]-y)/(yr[1]-yr[0])*(h-2*pad);ctx.strokeStyle='#bbb';ctx.strokeRect(pad,pad,w-2*pad,h-2*pad);ctx.strokeStyle='#111';ctx.lineWidth=3;ctx.beginPath();poses.forEach((p,i)=>i?ctx.lineTo(px(p.p[0]),py(p.p[1])):ctx.moveTo(px(p.p[0]),py(p.p[1])));ctx.stroke();const s=minJerk(tau),a=poses[0].p,b=poses[150].p,p=a.map((v,i)=>v+s*(b[i]-v));dot(ctx,px(p[0]),py(p[1]),'#e00000',7);ctx.fillStyle='#111';ctx.font='12px Arial';ctx.fillText('edge 1',px(.55)-48,py(0));ctx.fillText('x',w/2,h-8);ctx.save();ctx.translate(12,h/2);ctx.rotate(-PI/2);ctx.fillText('y',0,0);ctx.restore();}
function drawTiming(ctx,w,h,tau){const pad={l:48,r:15,t:17,b:29},pw=w-pad.l-pad.r,band=(h-pad.t-pad.b)/3,X=t=>pad.l+t*pw,plots=[{name:'s',color:'#111',fn:minJerk,range:[0,1]},{name:'ds/dτ',color:'#2474d2',fn:t=>30*t*t*(1-t)*(1-t),range:[0,1.9]},{name:'d²s/dτ²',color:'#e00000',fn:t=>60*t*(1-t)*(1-2*t),range:[-6,6]}];plots.forEach((plot,k)=>{const top=pad.t+k*band,Y=v=>top+band-(v-plot.range[0])/(plot.range[1]-plot.range[0])*(band-8)-4;ctx.strokeStyle='#ccc';ctx.strokeRect(pad.l,top,pw,band);if(plot.range[0]<0){ctx.strokeStyle='#999';ctx.beginPath();ctx.moveTo(pad.l,Y(0));ctx.lineTo(pad.l+pw,Y(0));ctx.stroke();}ctx.strokeStyle=plot.color;ctx.lineWidth=2.4;ctx.beginPath();for(let i=0;i<=180;i++){const t=i/180;i?ctx.lineTo(X(t),Y(plot.fn(t))):ctx.moveTo(X(t),Y(plot.fn(t)));}ctx.stroke();ctx.fillStyle=plot.color;ctx.font='11px Arial';ctx.fillText(plot.name,6,top+band/2+4);});ctx.strokeStyle='#555';ctx.beginPath();ctx.moveTo(X(tau),pad.t);ctx.lineTo(X(tau),h-pad.b);ctx.stroke();ctx.fillStyle='#111';ctx.textAlign='center';ctx.fillText('τ',pad.l+pw/2,h-7);ctx.textAlign='left';}

async function planning(viewer){
  if(!planningPromise)planningPromise=(async()=>{const data=await loadData(),targets=resampleMinimumJerk(data.poses,36),target0=targets[0].T,seeds=data.seeds.map(q=>{const s=q.slice();s[FREE]=FIXED_Q3;return s;}),known=data.reference[0].slice(),roots=[];known[FREE]=FIXED_Q3;
    for(const seed of [known,...seeds]){const s=solveFixed(viewer.model,target0,seed,FIXED_Q3,45);if(s&&!roots.some(r=>jointDistance(r,s.q)<.08))roots.push(s.q);}
    for(let i=0;i<48&&roots.length<8;i++){const s=known.map((v,j)=>j===FREE?FIXED_Q3:wrap(v+(((i>>(j%5))&1)?PI:-PI)*(j%2?.65:.35))),r=solveFixed(viewer.model,target0,s,FIXED_Q3,60);if(r&&!roots.some(q=>jointDistance(q,r.q)<.08))roots.push(r.q);}
    while(roots.length<8)roots.push((roots[roots.length%Math.max(1,roots.length)]||known).slice());
    const tracks=roots.slice(0,8).map((seed,index)=>track(viewer.model,targets,seed,index));return{...data,targets,tracks};})();
  return planningPromise;
}

async function createPlanningLab(host,mode){
  host.className+=' l8-lab l8-planning';host.innerHTML='<div class="l8-stage"><div class="hud">KUKA iiwa 7 · q₃ = 30° · analytical branch lift</div></div><aside><div class="l8-pills"></div><div class="l8-controls"><button class="primary" data-play>Play selected</button><button data-next>Next admissible</button></div><div class="l8-live-eq"><b>Equations at the current sample</b><span>τₖ = (k mod Nₑ)/Nₑ</span><span>sₖ = 10τₖ³ − 15τₖ⁴ + 6τₖ⁵</span><span>Tₖ = [p(sₖ), R(sₖ)]</span><span>q̄ₖ = IK<sub>branch</sub>(Tₖ; q₃=30°)</span></div><div class="l8-readout">Solving eight fixed-q₃ continuations…</div><progress max="1" value="0"></progress><p class="l8-status"></p></aside>';
  const stage=host.querySelector('.l8-stage'),pills=host.querySelector('.l8-pills'),play=host.querySelector('[data-play]'),next=host.querySelector('[data-next]'),readout=host.querySelector('.l8-readout'),progress=host.querySelector('progress'),status=host.querySelector('.l8-status'),{createModelViewer}=await api(),viewer=await createModelViewer(stage,'iiwa',{embedded:true,showEeFrame:true}),result=await planning(viewer);let selected=0,frame=0,playing=false,start=0;
  const visible=t=>mode==='filter'||mode==='play'?t.valid:true,render=()=>{pills.innerHTML=result.tracks.map((t,i)=>`<button data-i="${i}" class="${i===selected?'selected ':''}${visible(t)?'valid':'invalid'}" style="--branch:${COLORS[i]}">IK ${i+1}<small>${t.aspect}</small></button>`).join('');pills.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{selected=+b.dataset.i;frame=0;playing=false;refresh();render();}));};
  function refresh(){const t=result.tracks[selected],q=t.q[Math.min(frame,t.q.length-1)]||t.q[0],sample=result.targets[Math.min(frame,result.targets.length-1)];viewer.update(q);viewer.setTrace(result.targets.slice(0,frame+1).map(x=>new THREE.Vector3(...x.p)));progress.value=frame/Math.max(1,t.q.length-1);const tau=sample?.tau??0,s=minJerk(tau);readout.textContent=`IK ${selected+1} · ${t.aspect}\nedge ${(sample?.edge??0)+1} · τ=${tau.toFixed(3)} · s=${s.toFixed(3)}\nsample ${frame+1}/${t.q.length}\nmin |det J̄| = ${t.minDet.toExponential(2)}\nmax pose error = ${t.maxError.toExponential(2)}\nmax Δq = ${(t.maxStep/DEG).toFixed(1)}° · clearance = ${(1000*t.minClearance).toFixed(0)} mm\n${t.valid?'VIOLATION FREE':t.violations.join(' · ')}`;status.textContent=description(mode,result.tracks,t);}
  play.addEventListener('click',()=>{playing=!playing;if(playing){if(frame>=result.tracks[selected].q.length-1)frame=0;start=performance.now()-frame*38;}play.textContent=playing?'Pause':'Play selected';});next.addEventListener('click',()=>{const ok=result.tracks.map((t,i)=>t.valid?i:-1).filter(i=>i>=0),at=ok.indexOf(selected);selected=ok[(at+1+ok.length)%ok.length]??0;frame=0;playing=false;render();refresh();});
  function animate(time){if(playing){const t=result.tracks[selected],i=Math.min(t.q.length-1,Math.floor((time-start)/38));frame=i;refresh();if(i===t.q.length-1){playing=false;play.textContent='Replay selected';if(mode==='play')setTimeout(()=>next.click(),350);}}requestAnimationFrame(animate);}if(mode!=='play')next.textContent='Next branch';render();refresh();requestAnimationFrame(animate);
}
function description(mode,tracks,t){const pos=tracks.filter(x=>x.aspect==='aspect A⁺').length,neg=tracks.length-pos,ok=tracks.filter(x=>x.valid).length;if(mode==='enumerate')return`${tracks.length} numerical IK seeds are continued from the first pose; select a row to inspect its complete joint vector and residual.`;if(mode==='aspects')return`Reduced-Jacobian sign separates the regular lifts: ${pos} in A⁺ and ${neg} in A⁻. A sign change would require det J̄ = 0.`;if(mode==='filter')return`${ok} of ${tracks.length} lifts pass joint limits, continuity, reduced-singularity, and obstacle-clearance checks.`;return`Playing admissible lifts one by one. Current branch: ${t.aspect}; the workspace command is identical, but joint travel and clearance differ.`;}

function track(model,targets,seed,index,fixed=FIXED_Q3){const qs=[seed.slice()];let q=seed.slice(),maxError=0,minDet=Infinity,failed=false,maxStep=0,minClearance=Infinity;for(let i=1;i<targets.length;i++){const s=solveFixed(model,targets[i].T,q,fixed,24);if(!s){failed=true;break;}maxStep=Math.max(maxStep,jointDistance(q,s.q));q=s.q;qs.push(q);maxError=Math.max(maxError,s.error);minDet=Math.min(minDet,Math.abs(s.det));const elbow=model.point(q,'iiwa_link_4'),dx=Math.max(Math.abs(elbow.x-.72)-.08,0),dy=Math.max(Math.abs(elbow.y-.58)-.08,0),dz=Math.max(Math.abs(elbow.z-.45)-.12,0);minClearance=Math.min(minClearance,Math.hypot(dx,dy,dz)-.055);}
  const limit=qs.some(q=>q.some((v,j)=>Math.abs(wrap(v))>LIMITS[j])),singular=failed||minDet<2e-4,continuity=maxStep>1.05,obstacle=minClearance<0,violations=[];if(limit)violations.push('joint limit');if(singular)violations.push('singularity / IK loss');if(continuity)violations.push('discontinuity');if(obstacle)violations.push('obstacle');const det=jacobian(model,qs[0]).det,aspect=det>=0?'aspect A⁺':'aspect A⁻';return{index,q:qs,aspect,minDet,maxError,maxStep,minClearance,violations,valid:!violations.length};}

function resampleMinimumJerk(poses,n=36){const corners=[0,150,250,399,499],out=[];for(let e=0;e<4;e++){const a=poses[corners[e]],b=poses[corners[e+1]];for(let i=0;i<n;i++){const tau=i/n,s=minJerk(tau),p=a.p.map((v,j)=>v+s*(b.p[j]-v)),q=a.q.clone().slerp(b.q,s),T=new THREE.Matrix4().compose(new THREE.Vector3(...p),q,new THREE.Vector3(1,1,1));out.push({p,q,T,edge:e,tau});}}out.push({...poses[corners[4]],edge:3,tau:1});return out;}
function minJerk(t){return 10*t**3-15*t**4+6*t**5;}

async function createGlobalMap(host){
  host.className+=' l8-lab l8-global';host.innerHTML='<div class="l8-map-wrap"><canvas></canvas><div class="l8-map-legend"><span><i class="green"></i>regular and within limits</span><span><i class="grey"></i>violated / no continuation</span><span><i class="corridor"></i>one feasible q₃ schedule</span></div></div><aside><label>Analytical branch <select></select></label><button class="primary" data-build>Build 1001 × 37 map</button><div class="l8-readout">Select one of the eight q₃=30° branches.</div><progress max="37" value="0"></progress><p class="l8-status">Each cell asks whether that branch can realize pose k at the selected constant q₃ value.</p></aside>';
  const canvas=host.querySelector('canvas'),select=host.querySelector('select'),button=host.querySelector('[data-build]'),readout=host.querySelector('.l8-readout'),status=host.querySelector('.l8-status'),progress=host.querySelector('progress'),{createModelViewer}=await api(),scratch=document.createElement('div');scratch.style.cssText='position:absolute;width:2px;height:2px;overflow:hidden';host.append(scratch);const viewer=await createModelViewer(scratch,'iiwa',{embedded:true}),base=await planning(viewer),targets=resampleMinimumJerk(base.poses,250),q3s=Array.from({length:37},(_,i)=>(-90+5*i)*DEG),cache=new Map(),pair=canvasKit(canvas,draw);let matrix=null,corridor=[],busy=false;
  base.tracks.forEach((t,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`IK ${i+1} · ${t.aspect}`;select.append(o);});
  async function build(){if(busy)return;const branch=+select.value;if(cache.has(branch)){({matrix,corridor}=cache.get(branch));draw();describe(branch);return;}busy=true;button.disabled=true;button.textContent='Continuing analytical branch…';matrix=Array.from({length:q3s.length},()=>new Uint8Array(targets.length));const order=[24,...Array.from({length:18},(_,i)=>25+i).filter(i=>i<37),...Array.from({length:24},(_,i)=>23-i)],roots=new Map([[24,base.tracks[branch].q[0].slice()]]),rowAnchors=new Map();
    for(let oi=0;oi<order.length;oi++){const row=order[oi],direction=row>24?-1:1,neighborRow=row+direction,neighbor=roots.get(neighborRow),root=neighbor&&solveFixed(viewer.model,targets[0].T,neighbor,q3s[row],38);if(root){roots.set(row,root.q);const step=50,neighborAnchors=rowAnchors.get(neighborRow)||[],anchors=[{k:0,q:root.q,det:root.det}];let q=root.q;for(let k=step;k<targets.length;k+=step){const crossSeed=neighborAnchors.find(a=>a.k===k)?.q||q,s=solveFixed(viewer.model,targets[k].T,crossSeed,q3s[row],22);if(!s)break;q=s.q;anchors.push({k,q:q.slice(),det:s.det});}rowAnchors.set(row,anchors);for(let a=0;a<anchors.length-1;a++){const u=anchors[a],v=anchors[a+1];for(let k=u.k;k<=v.k;k++){const t=(k-u.k)/(v.k-u.k),qi=u.q.map((x,j)=>wrap(x+t*wrap(v.q[j]-x))),e=poseError(viewer.model.pose(qi),targets[k].T),det=(1-t)*u.det+t*v.det,limits=qi.every((x,j)=>Math.abs(wrap(x))<=LIMITS[j]);matrix[row][k]=e.norm<3e-2&&Math.abs(det)>2e-4&&u.det*v.det>0&&limits?1:0;}}}progress.value=oi+1;readout.textContent=`branch IK ${branch+1}\nq₃ row ${oi+1}/37\n1001 cells evaluated · branch anchors every 50 samples`;draw();await new Promise(requestAnimationFrame);}
    corridor=findCorridor(matrix,24);cache.set(branch,{matrix,corridor});busy=false;button.disabled=false;button.textContent='Rebuild selected branch';describe(branch);draw();
  }
  function describe(branch){const green=matrix.reduce((n,row)=>n+row.reduce((a,v)=>a+v,0),0),complete=corridor.filter(v=>v>=0).length===targets.length;readout.textContent=`IK ${branch+1} · ${base.tracks[branch].aspect}\ngreen cells ${green}/${targets.length*q3s.length}\nq₃ grid −90°…90° in 5° steps\n${complete?'continuous green corridor reaches sample 1000':'no complete sampled corridor'}`;status.textContent=complete?'Modulating q₃ along the white corridor preserves the selected analytical branch through the entire path.':'The grey barrier exposes a global obstruction: this branch cannot reach the end within the sampled q₃ range and constraints.';}
  function draw(){if(!pair.ready)return;const {ctx,w,h}=pair;clear(ctx,w,h);const pad={l:54,r:15,t:20,b:35},pw=w-pad.l-pad.r,ph=h-pad.t-pad.b;ctx.fillStyle='#d8dadd';ctx.fillRect(pad.l,pad.t,pw,ph);if(matrix){const cw=pw/targets.length,ch=ph/q3s.length;ctx.fillStyle='#42a85a';for(let r=0;r<matrix.length;r++)for(let k=0;k<matrix[r].length;k++)if(matrix[r][k])ctx.fillRect(pad.l+k*cw,pad.t+(matrix.length-1-r)*ch,Math.max(1,cw+.2),Math.max(1,ch+.2));if(corridor.length){ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();corridor.forEach((r,k)=>{if(r<0)return;const x=pad.l+k*cw,y=pad.t+(matrix.length-1-r+.5)*ch;k?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.stroke();}}ctx.strokeStyle='#777';ctx.strokeRect(pad.l,pad.t,pw,ph);ctx.fillStyle='#111';ctx.font='11px Arial';ctx.textAlign='right';ctx.fillText('90°',pad.l-6,pad.t+5);ctx.fillText('0°',pad.l-6,pad.t+ph/2+4);ctx.fillText('−90°',pad.l-6,pad.t+ph);ctx.textAlign='center';ctx.fillText('path sample k = 0 … 1000',pad.l+pw/2,h-8);ctx.save();ctx.translate(13,pad.t+ph/2);ctx.rotate(-PI/2);ctx.fillText('fixed q₃ value',0,0);ctx.restore();ctx.textAlign='left';}
  button.addEventListener('click',build);select.addEventListener('change',()=>{matrix=null;corridor=[];progress.value=0;draw();status.textContent='Press build to continue this analytical branch over the complete q₃ grid.';});build();
}
function findCorridor(matrix,start){const rows=matrix.length,cols=matrix[0]?.length||0,out=Array(cols).fill(-1),parents=Array.from({length:cols},()=>new Int16Array(rows).fill(-1));let reachable=new Uint8Array(rows);if(matrix[start]?.[0])reachable[start]=1;else{let nearest=-1;for(let d=1;d<rows&&nearest<0;d++)for(const r of[start-d,start+d])if(matrix[r]?.[0]){nearest=r;break;}if(nearest>=0)reachable[nearest]=1;}let last=0;for(let k=1;k<cols;k++){const next=new Uint8Array(rows);for(let r=0;r<rows;r++)if(matrix[r][k])for(const p of[r,r-1,r+1])if(p>=0&&p<rows&&reachable[p]){next[r]=1;parents[k][r]=p;break;}if(!next.some(Boolean))break;reachable=next;last=k;}let r=-1,d=Infinity;for(let j=0;j<rows;j++)if(reachable[j]&&Math.abs(j-start)<d){r=j;d=Math.abs(j-start);}if(r<0)return out;for(let k=last;k>=0;k--){out[k]=r;if(k)r=parents[k][r];}return out;}

function solveFixed(model,target,seed,fixed,iterations=32){let q=seed.slice();q[FREE]=fixed;for(let k=0;k<iterations;k++){const current=model.pose(q),e=poseError(current,target);if(e.norm<2e-6){const j=jacobian(model,q);return{q,error:e.norm,det:j.det};}const j=jacobian(model,q),dq=solveLinearDamped(j.A,e.v,1e-7);if(!dq||dq.some(v=>!Number.isFinite(v)))return null;const scale=Math.max(1,Math.hypot(...dq)/.28);ACTIVE.forEach((joint,i)=>q[joint]=wrap(q[joint]+dq[i]/scale));q[FREE]=fixed;}const e=poseError(model.pose(q),target);return e.norm<2e-4?{q,error:e.norm,det:jacobian(model,q).det}:null;}
function jacobian(model,q){if(model.geometricJacobian){const G=model.geometricJacobian(q),A=Array.from({length:6},(_,r)=>ACTIVE.map(j=>G.columns[j][r]));return{A,det:determinant(A)};}const h=2e-5,base=model.pose(q),A=Array.from({length:6},()=>Array(6));ACTIVE.forEach((joint,c)=>{const p=q.slice();p[joint]+=h;const d=poseDelta(base,model.pose(p));for(let r=0;r<6;r++)A[r][c]=d[r]/h;});return{A,det:determinant(A)};}
function poseError(current,target){const cp=new THREE.Vector3().setFromMatrixPosition(current),tp=new THREE.Vector3().setFromMatrixPosition(target),dp=tp.sub(cp),r=rotationVector(new THREE.Matrix4().extractRotation(target).multiply(new THREE.Matrix4().extractRotation(current).transpose()));const v=[dp.x,dp.y,dp.z,...r],norm=Math.hypot(...v);return{v,norm};}
function poseDelta(a,b){const ap=new THREE.Vector3().setFromMatrixPosition(a),bp=new THREE.Vector3().setFromMatrixPosition(b),d=bp.sub(ap),r=rotationVector(new THREE.Matrix4().extractRotation(b).multiply(new THREE.Matrix4().extractRotation(a).transpose()));return[d.x,d.y,d.z,...r];}
function rotationVector(R){const q=new THREE.Quaternion().setFromRotationMatrix(R).normalize();if(q.w<0)q.set(-q.x,-q.y,-q.z,-q.w);const s=Math.hypot(q.x,q.y,q.z);if(s<1e-12)return[0,0,0];const a=2*Math.atan2(s,q.w);return[q.x/s*a,q.y/s*a,q.z/s*a];}
function solveLinearDamped(A,b,lambda){const At=A[0].map((_,c)=>A.map(r=>r[c])),N=At.map((row,i)=>row.map((_,j)=>row.reduce((s,v,k)=>s+v*A[k][j],0)+(i===j?lambda:0))),rhs=At.map(row=>row.reduce((s,v,k)=>s+v*b[k],0));return gaussian(N,rhs);}
function gaussian(A,b){const M=A.map((r,i)=>[...r,b[i]]),n=b.length;for(let c=0;c<n;c++){let p=c;for(let r=c+1;r<n;r++)if(Math.abs(M[r][c])>Math.abs(M[p][c]))p=r;if(Math.abs(M[p][c])<1e-13)return null;[M[c],M[p]]=[M[p],M[c]];for(let r=c+1;r<n;r++){const f=M[r][c]/M[c][c];for(let j=c;j<=n;j++)M[r][j]-=f*M[c][j];}}const x=Array(n);for(let i=n-1;i>=0;i--){let s=M[i][n];for(let j=i+1;j<n;j++)s-=M[i][j]*x[j];x[i]=s/M[i][i];}return x;}
function determinant(A){const M=A.map(r=>r.slice()),n=M.length;let d=1;for(let c=0;c<n;c++){let p=c;for(let r=c+1;r<n;r++)if(Math.abs(M[r][c])>Math.abs(M[p][c]))p=r;if(Math.abs(M[p][c])<1e-14)return 0;if(p!==c){[M[c],M[p]]=[M[p],M[c]];d=-d;}d*=M[c][c];for(let r=c+1;r<n;r++){const f=M[r][c]/M[c][c];for(let j=c+1;j<n;j++)M[r][j]-=f*M[c][j];}}return d;}
function jointDistance(a,b){return Math.hypot(...a.map((v,i)=>wrap(v-b[i])));}
function wrap(a){return Math.atan2(Math.sin(a),Math.cos(a));}

function canvasKit(canvas,draw){const s={canvas,ctx:canvas.getContext('2d'),w:0,h:0,ready:false},resize=()=>{const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);if(r.width<2||r.height<2)return;canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);s.ctx.setTransform(d,0,0,d,0,0);s.w=r.width;s.h=r.height;s.ready=true;draw();};new ResizeObserver(resize).observe(canvas);requestAnimationFrame(resize);return s;}
function clear(ctx,w,h){ctx.clearRect(0,0,w,h);ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);}
function dot(ctx,x,y,color,r){ctx.beginPath();ctx.arc(x,y,r,0,2*PI);ctx.fillStyle=color;ctx.fill();ctx.strokeStyle='#111';ctx.stroke();}
function fail(host,error){host.innerHTML=`<div class="warning">Lecture 08 visualization could not start: ${String(error.message).replace(/[&<>]/g,'')}</div>`;console.error(error);}
