import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { createZUpWorld, resizeRendererToContainer } from './threeUtils.js';
import { parseStlGeometry } from './frameDHPlayground.js?v=20260814-3';

const PI = Math.PI;
const DEG = PI / 180;
const MODULE_REVISION = new URL(import.meta.url).searchParams.get('v') || 'dev';
const COLORS = ['#e00000', '#2474d2', '#65a34a', '#d18b00', '#8b62a8', '#008f95'];
const MODEL_SPECS = {
  '3r-zero': { urdf: '../../assets/models/custom_3R/custom_3R_new_0.urdf', mesh: '../../assets/models/custom_3R/', end: 'tool0', q: [25,-35,55], camera: [10,9,8], target: [2,1,.7] },
  '3r-offset': { urdf: '../../assets/models/custom_3R/custom_3R_new.urdf', mesh: '../../assets/models/custom_3R/', end: 'tool0', q: [25,-35,55], camera: [10,9,8], target: [2,1,.7] },
  'custom-6r': { urdf: '../../assets/models/custom_6R/custom_6R_new.urdf', mesh: '../../assets/models/custom_6R/', end: 'link_6', q: [-60,20,120,35,-50,70], camera: [14,12,10], target: [3,1.4,1], frameScale: .7 },
  puma: { urdf: '../../assets/models/puma/puma560_robot.urdf', mesh: '../../assets/models/puma/', end: 'link7', q: [30,-35,45,40,-50,60], camera: [2.4,2.1,1.7], target: [.1,0,.65], frameScale: .11 },
  iiwa: { urdf: '../../assets/models/iiwa7/iiwa7_free_joints.urdf', mesh: '../../assets/models/iiwa7/', end: 'iiwa_link_ee', q: [20,-35,30,50,-40,45,60], camera: [1.7,1.5,1.25], target: [.1,0,.62], frameScale: .11 },
  fanuc: { urdf: '../../assets/models/fanuc_crx10ia_support/crx10ial.urdf', mesh: '../../assets/models/fanuc_crx10ia_support/', end: 'link_6', q: [15,-30,55,20,40,-25], camera: [2.7,2.4,2.1], target: [.3,0,.7], frameScale: .16 }
};
const PRESETS = {
  noncuspidal: { a1: 0, a2: 2, a3: 1.5, d1: 1, d2: 1, d3: 0, A1: PI/2, A2: PI/2, A3: 0 },
  cuspidal: { a1: 1, a2: 2, a3: 1.5, d1: 1, d2: 1, d3: 0, A1: PI/2, A2: PI/2, A3: 0 }
};
const CUSTOM_3R_URDF_DH = { a1: 1, a2: 2, a3: 1.5, d1: 1, d2: 1.25, d3: .75, A1: -PI/2, A2: PI/2, A3: 0 };

export function initCuspidalityLecture() {
  const labs = [...document.querySelectorAll('[data-cusp-lab]')];
  const models = [...document.querySelectorAll('[data-cusp-model]')];
  if (!labs.length && !models.length) return;
  const initialized = new WeakSet();
  const ensure = (host) => {
    if (initialized.has(host)) return;
    initialized.add(host);
    const mode = host.dataset.cuspLab || host.dataset.cuspModel;
    try {
      if (host.dataset.cuspModel) createModelViewer(host, mode).catch((error) => fail(host,error));
      else if (mode === 'two-r') create2RAspectLab(host);
      else if (mode === 'atlas-3r') createAtlas3R(host);
      else if (mode === 'nscs-3r') createNscsLab(host).catch((error)=>fail(host,error));
      else if (mode === 'custom-6r') createCustom6RLab(host);
      else if (mode === 'puma-6r') createPartitioned6RLab(host,'puma').catch((error)=>fail(host,error));
      else if (mode === 'fanuc-16') createFanuc16Lab(host).catch((error)=>fail(host,error));
    } catch (error) { fail(host,error); }
  };
  const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) ensure(entry.target); }), { threshold: .02, rootMargin: '100px' });
  [...labs,...models].forEach((host) => observer.observe(host));
  const sync = () => { const n = Number(location.hash.match(/#slide-(\d+)/)?.[1] || 1); document.querySelectorAll('#deck > .slide')[n-1]?.querySelectorAll('[data-cusp-lab],[data-cusp-model]').forEach(ensure); };
  sync(); window.addEventListener('hashchange',sync);
  runChecks();
}

function fail(host,error) { host.innerHTML = `<div class="warning">Cuspidality visualization could not start: ${escapeHtml(error.message)}</div>`; console.error(error); }

function create2RAspectLab(host) {
  host.className += ' cusp-lab cusp-two';
  host.innerHTML = '<div class="cusp-plot"><h3>joint space</h3><canvas data-joint></canvas></div><div class="cusp-plot"><h3>workspace</h3><canvas data-work></canvas></div><aside class="cusp-side"><h3>2R branch separator</h3><div data-ranges></div><div class="cusp-formula">det(J) = l₁l₂ sin(q₂)\n\nq₂ = 0 or ±π is singular.</div><div class="cusp-status" data-status></div><div class="cusp-legend"><span><i style="background:#2474d2"></i>elbow up</span><span><i style="background:#65a34a"></i>elbow down</span><span><i style="background:#e00000"></i>singular</span></div></aside>';
  const jc = host.querySelector('[data-joint]'), wc = host.querySelector('[data-work]'), ranges = host.querySelector('[data-ranges]');
  const state = { q1: .55, q2: 1.15, l1: 1.15, l2: .82 };
  addRange(ranges,'q₁',-180,180,1,state.q1/DEG,(v)=>{state.q1=v*DEG;draw();});
  addRange(ranges,'q₂',-180,180,1,state.q2/DEG,(v)=>{state.q2=v*DEG;draw();});
  addRange(ranges,'l₁',.5,1.5,.05,state.l1,(v)=>{state.l1=v;draw();},' m');
  addRange(ranges,'l₂',.5,1.5,.05,state.l2,(v)=>{state.l2=v;draw();},' m');
  const pair = resizeCanvases([jc,wc],draw);
  function fk(q1,q2) { return [state.l1*Math.cos(q1)+state.l2*Math.cos(q1+q2),state.l1*Math.sin(q1)+state.l2*Math.sin(q1+q2)]; }
  function draw() {
    if (!pair.ready()) return;
    const [jctx,wctx]=pair.contexts, [js,ws]=pair.sizes; clear(jctx,js); clear(wctx,ws);
    const jm=plotMap(js,[-PI,PI],[-PI,PI],{x:'q₁',y:'q₂'}); axes(jctx,jm);
    fillPlot(jctx,jm,[-PI,PI],[0,PI],'rgba(36,116,210,.12)'); fillPlot(jctx,jm,[-PI,PI],[-PI,0],'rgba(101,163,74,.12)');
    [0,-PI,PI].forEach((q)=>polyline(jctx,[[-PI,q],[PI,q]],jm,'#e00000',3));
    const target=fk(state.q1,state.q2),mirrorQ2=-state.q2,mirrorQ1=Math.atan2(target[1],target[0])-Math.atan2(state.l2*Math.sin(mirrorQ2),state.l1+state.l2*Math.cos(mirrorQ2));
    dot(jctx,jm.toPx(state.q1,state.q2),COLORS[state.q2>=0?1:2],7,'#111');dot(jctx,jm.toPx(wrap(mirrorQ1),mirrorQ2),COLORS[state.q2>=0?2:1],7,'#111');
    const reach=state.l1+state.l2, inner=Math.abs(state.l1-state.l2), wm=plotMap(ws,[-reach*1.15,reach*1.15],[-reach*1.15,reach*1.15],{x:'x',y:'y'}); axes(wctx,wm);
    circlePlot(wctx,wm,reach,'#e00000',3); circlePlot(wctx,wm,inner,'#e00000',3);
    const p=target,e=[state.l1*Math.cos(state.q1),state.l1*Math.sin(state.q1)],em=[state.l1*Math.cos(mirrorQ1),state.l1*Math.sin(mirrorQ1)],o=wm.toPx(0,0),ep=wm.toPx(...e),emp=wm.toPx(...em),pp=wm.toPx(...p);
    polylinePx(wctx,[o,emp,pp],COLORS[state.q2>=0?2:1],7);polylinePx(wctx,[o,ep,pp],COLORS[state.q2>=0?1:2],9);dot(wctx,o,'#fff',6,'#111');dot(wctx,ep,'#fff',5,'#111');dot(wctx,emp,'#fff',5,'#111');dot(wctx,pp,'#111',8,'#fff');
    const det=state.l1*state.l2*Math.sin(state.q2); host.querySelector('[data-status]').textContent=`Current branch: ${state.q2>=0?'elbow up':'elbow down'} · det(J) = ${det.toFixed(3)} m² · aspect ${state.q2>=0?'A₊':'A₋'}`;
  }
  bindDrag(jc,(x,y)=>{state.q1=x;state.q2=y;syncRanges(ranges,[state.q1/DEG,state.q2/DEG,state.l1,state.l2]);draw();},()=>plotMap(pair.sizes[0],[-PI,PI],[-PI,PI]));
  bindDrag(wc,(x,y)=>{const r2=x*x+y*y,c2=clamp((r2-state.l1**2-state.l2**2)/(2*state.l1*state.l2),-1,1),sign=state.q2>=0?1:-1;state.q2=sign*Math.acos(c2);state.q1=Math.atan2(y,x)-Math.atan2(state.l2*Math.sin(state.q2),state.l1+state.l2*Math.cos(state.q2));syncRanges(ranges,[state.q1/DEG,state.q2/DEG,state.l1,state.l2]);draw();},()=>{const r=state.l1+state.l2;return plotMap(pair.sizes[1],[-r*1.15,r*1.15],[-r*1.15,r*1.15]);});
  draw();
}

function createAtlas3R(host, options={}) {
  host.className += ' cusp-lab cusp-atlas';
  host.innerHTML = '<div class="cusp-plot-row"><div class="cusp-plot"><h3>joint space · q₂,q₃ ∈ [−π,π]</h3><canvas data-joint></canvas></div><div class="cusp-plot"><h3>workspace critical values · ρ,z</h3><canvas data-work></canvas></div></div><div class="cusp-controls"><div><div class="cusp-presets"><button data-preset="noncuspidal">3R zero offset</button><button data-preset="cuspidal" class="active">3R offset</button></div><div class="cusp-iks" data-iks></div></div><div class="cusp-control-grid" data-params></div><div><div class="cusp-formula" data-formula></div><div class="cusp-status" data-status>Click the workspace plot to solve IK.</div></div></div>';
  const jc=host.querySelector('[data-joint]'),wc=host.querySelector('[data-work]'),paramsHost=host.querySelector('[data-params]'),state={p:{...PRESETS.cuspidal},solutions:[],target:null,map:null,cache:null};
  const controls=[['a₁','a1',0,2,.1],['a₂','a2',.4,3,.1],['a₃','a3',.4,3,.1],['d₂','d2',0,2,.1],['d₃','d3',0,1.5,.1],['α₁','A1',-180,180,5],['α₂','A2',-180,180,5],['α₃','A3',-180,180,5]];
  controls.forEach(([label,key,min,max,step])=>{const el=document.createElement('label');el.innerHTML=`${label}<input type="number" min="${min}" max="${max}" step="${step}" data-key="${key}">`;el.querySelector('input').addEventListener('change',(e)=>{state.p[key]=Number(e.target.value)*(key[0]==='A'?DEG:1);host.querySelectorAll('[data-preset]').forEach(b=>b.classList.remove('active'));rebuild();});paramsHost.append(el);});
  const syncInputs=()=>paramsHost.querySelectorAll('input').forEach((input)=>{const v=state.p[input.dataset.key];input.value=(input.dataset.key[0]==='A'?v/DEG:v).toFixed(input.dataset.key[0]==='A'?0:2);});
  host.querySelectorAll('[data-preset]').forEach((button)=>button.addEventListener('click',()=>{state.p={...PRESETS[button.dataset.preset]};host.querySelectorAll('[data-preset]').forEach(b=>b.classList.toggle('active',b===button));syncInputs();rebuild();}));
  const pair=resizeCanvases([jc,wc],draw); syncInputs();
  function rebuild(){state.cache=buildSingularityCache(state.p);state.target=sliceFk([-10*DEG,-170*DEG],state.p);state.solutions=solveIkSlice(state.target,state.p);host.querySelector('[data-iks]').innerHTML=state.solutions.map((q,i)=>`<button style="border-color:${COLORS[i%COLORS.length]}">IK ${i+1}</button>`).join('');host.querySelector('[data-formula]').textContent=factorText(state.p);host.querySelector('[data-status]').textContent=`Example target loaded · ${state.solutions.length} regular IK solutions. Click anywhere in the workspace slice to solve again.`;draw();}
  function draw(){if(!pair.ready()||!state.cache)return;const [jctx,wctx]=pair.contexts,[js,ws]=pair.sizes;clear(jctx,js);clear(wctx,ws);const jm=plotMap(js,[-PI,PI],[-PI,PI],{x:'q₂',y:'q₃'}),wm=plotMap(ws,state.cache.rhoRange,state.cache.zRange,{x:'ρ',y:'z'});state.map=wm;axes(jctx,jm);axes(wctx,wm);drawSegments(jctx,state.cache.singularSegments,jm,'#e00000',2);state.cache.criticalBranches.forEach(branch=>polyline(wctx,branch,wm,'#e00000',2));if(state.target)dot(wctx,wm.toPx(...state.target),'#111',7,'#fff');state.solutions.forEach((q,i)=>dot(jctx,jm.toPx(q[0],q[1]),COLORS[i%COLORS.length],7,'#111'));}
  wc.addEventListener('pointerdown',(event)=>{const rect=wc.getBoundingClientRect(),p=state.map.fromPx(event.clientX-rect.left,event.clientY-rect.top);state.target=[Math.max(0,p[0]),p[1]];state.solutions=solveIkSlice(state.target,state.p);const pills=host.querySelector('[data-iks]');pills.innerHTML=state.solutions.map((q,i)=>`<button style="border-color:${COLORS[i%COLORS.length]}">IK ${i+1}</button>`).join('');host.querySelector('[data-status]').textContent=state.solutions.length?`${state.solutions.length} regular IK solutions found · colored points are plotted in joint space.`:'No regular IK solution at this point.';draw();});
  rebuild();
  return { state, rebuild, draw };
}

async function createNscsLab(host) {
  host.className += ' cusp-lab cusp-nscs';
  host.innerHTML='<div class="cusp-nscs-panels"><div class="cusp-plot"><h3>joint space</h3><canvas data-joint></canvas></div><div class="cusp-plot"><h3>closed FK loop · ρ,z</h3><canvas data-work></canvas></div><div class="cusp-stage" data-stage><div class="hud">custom_3R_new.urdf · uploaded STL</div></div></div><div class="cusp-nscs-controls"><div class="cusp-iks" data-iks></div><div class="cusp-status" data-status>Loading the Lecture 03 IK solver.</div><div><button data-build disabled>Build path</button> <button data-play disabled>Play</button></div></div>';
  const jc=host.querySelector('[data-joint]'),wc=host.querySelector('[data-work]'),status=host.querySelector('[data-status]'),buildButton=host.querySelector('[data-build]'),playButton=host.querySelector('[data-play]'),state={p:{...CUSTOM_3R_URDF_DH},cache:null,target:null,solutions:[],selected:[],path:[],fullPath:[],trace:[],map:null,playing:false,solving:false};
  state.cache=buildSingularityCache(state.p);const pair=resizeCanvases([jc,wc],draw),[viewer,ikModule]=await Promise.all([createModelViewer(host.querySelector('[data-stage]'),'3r-offset',{embedded:true}),import(`./custom3rIk.js?v=${MODULE_REVISION}`)]);
  const solvePosition=async(position)=>ikModule.solveCustom3RPositionIk(position),solveFullIk=async(target)=>solvePosition([target[0],0,target[1]]);
  function clearPath(){state.selected=[];state.path=[];state.fullPath=[];state.trace=[];buildButton.disabled=true;playButton.disabled=true;}
  function constructPath(){if(state.selected.length!==2)return[];const qa=state.solutions[state.selected[0]],qb=state.solutions[state.selected[1]],slicePath=planAspectPath(qa.slice(1),qb.slice(1),state.p);if(!slicePath.length)return[];state.path=slicePath;state.fullPath=slicePath.map((slice,i)=>[angleLerp(qa[0],qb[0],i/Math.max(1,slicePath.length-1)),slice[0],slice[1]]);refresh3DMotion();return slicePath;}
  function refresh3DMotion(){if(!state.fullPath.length)return;const points=state.fullPath.map(q=>viewer.point(q));state.trace=points.map(p=>[Math.hypot(p.x,p.y),p.z]);viewer.setGhost(state.fullPath[0]);viewer.update(state.fullPath[0]);viewer.setTrace(points);}
  async function setTarget(target,chooseExample=false){state.solving=true;state.target=target;clearPath();status.textContent='Solving position IK with the Lecture 03 custom 3R solver.';draw();await new Promise(resolve=>setTimeout(resolve,0));state.solutions=(await solveFullIk(target)).filter(q=>Math.abs(det3(q,state.p))>1e-6);state.solving=false;if(chooseExample){outer:for(let i=0;i<state.solutions.length;i+=1)for(let j=i+1;j<state.solutions.length;j+=1){state.selected=[i,j];if(constructPath().length)break outer;state.selected=[];}}renderPills();buildButton.disabled=state.selected.length!==2;playButton.disabled=!state.fullPath.length;status.textContent=state.fullPath.length?`Ready example · IK ${state.selected[0]+1} and IK ${state.selected[1]+1} share one aspect. Their FK path starts and ends at the selected point.`:`${state.solutions.length} full position-IK solutions found at x = ρ, y = 0. Select two endpoints.`;draw();}
  function draw(){if(!pair.ready())return;const [jctx,wctx]=pair.contexts,[js,ws]=pair.sizes;clear(jctx,js);clear(wctx,ws);const jm=plotMap(js,[-PI,PI],[-PI,PI],{x:'q₂',y:'q₃'}),wm=plotMap(ws,state.cache.rhoRange,state.cache.zRange,{x:'ρ',y:'z'});state.map=wm;axes(jctx,jm);axes(wctx,wm);drawSegments(jctx,state.cache.singularSegments,jm,'#e00000',1.8);state.cache.criticalBranches.forEach(branch=>polyline(wctx,branch,wm,'#e00000',1.8));if(state.path.length)polylineTorus(jctx,state.path,jm,'#111',3);if(state.trace.length)polyline(wctx,state.trace,wm,'#2474d2',3);if(state.target)dot(wctx,wm.toPx(...state.target),'#111',7,'#fff');state.solutions.forEach((q,i)=>dot(jctx,jm.toPx(q[1],q[2]),COLORS[i%COLORS.length],state.selected.includes(i)?9:6,'#111'));}
  wc.addEventListener('pointerdown',async(event)=>{if(state.playing||state.solving)return;const rect=wc.getBoundingClientRect(),p=state.map.fromPx(event.clientX-rect.left,event.clientY-rect.top);await setTarget([Math.max(0,p[0]),p[1]]);});
  function renderPills(){const h=host.querySelector('[data-iks]');h.innerHTML=state.solutions.map((q,i)=>`<button data-i="${i}" class="${state.selected.includes(i)?'selected':''}" style="border-color:${COLORS[i%COLORS.length]}">IK ${i+1}</button>`).join('');h.querySelectorAll('button').forEach((b)=>b.addEventListener('click',()=>{const i=+b.dataset.i;if(state.selected.includes(i))state.selected=state.selected.filter(x=>x!==i);else if(state.selected.length<2)state.selected.push(i);state.path=[];state.fullPath=[];state.trace=[];renderPills();buildButton.disabled=state.selected.length!==2;playButton.disabled=true;draw();}));}
  buildButton.addEventListener('click',async()=>{const path=constructPath();if(!path.length){status.textContent='These IKs are not connected in the sampled aspect. Choose another pair.';playButton.disabled=true;draw();return;}buildButton.disabled=true;status.textContent='Checking the FK path against the Lecture 03 IK solver.';draw();const check=await verifyFullIkContinuation(state.fullPath,viewer,solvePosition),min=Math.min(...state.path.map(q=>Math.abs(det3([0,...q],state.p)))),closure=distance2(state.trace[0],state.trace.at(-1));status.textContent=`Closed FK loop · endpoint error ${closure.toExponential(2)} m · min |det J| ${min.toFixed(3)} · IK continuation ${check?'verified':'needs finer sampling'}.`;buildButton.disabled=false;playButton.disabled=false;draw();});
  playButton.addEventListener('click',()=>{if(!state.fullPath.length||state.playing)return;refresh3DMotion();state.playing=true;let start=performance.now();const duration=Math.max(4000,state.fullPath.length*55);const step=(now)=>{const u=Math.min(1,(now-start)/duration),x=u*(state.fullPath.length-1),i=Math.min(state.fullPath.length-2,Math.floor(x)),t=x-i,q=state.fullPath[i].map((v,k)=>angleLerp(v,state.fullPath[i+1][k],t));viewer.update(q);if(u<1)requestAnimationFrame(step);else state.playing=false;};requestAnimationFrame(step);});
  const seed=sliceFk([-10*DEG,-170*DEG],state.p);await setTarget(seed,true);
}

function createCustom6RLab(host) {
  createPartitioned6RLab(host,'custom-6r').catch((error)=>fail(host,error));
}

async function createPartitioned6RLab(host,key){
  host.className+=' cusp-lab cusp-partitioned';host.innerHTML='<div class="cusp-partition-panels"><div class="cusp-plot"><h3>positional singularities · q₂,q₃</h3><canvas data-joint></canvas></div><div class="cusp-plot"><h3>workspace slice · ρ,z</h3><canvas data-work></canvas></div><div class="cusp-stage" data-stage><div class="hud">fixed orientation · RGB ee frame · O<sub>w</sub>=(ρ,0,z)</div></div></div><div class="cusp-partition-controls"><div class="cusp-iks" data-iks></div><div class="cusp-status" data-status>Loading uploaded URDF and STL files.</div><label class="cusp-toggle"><input type="checkbox" data-autoplay> cycle through IKs</label></div>';
  if(key==='puma')host.querySelector('.hud').innerHTML='downward ee orientation · RGB frame · O<sub>w</sub>=(ρ,0,z)';
  const jc=host.querySelector('[data-joint]'),wc=host.querySelector('[data-work]'),status=host.querySelector('[data-status]'),state={solutions:[],selected:0,target:null,jmap:null,wmap:null,cache:null,lastCycle:0};let viewer;
  try{viewer=await createModelViewer(host.querySelector('[data-stage]'),key,{embedded:true,showEeFrame:true});}catch(error){fail(host,error);return;}
  const model=viewer.model,reference=MODEL_SPECS[key].q.map(v=>v*DEG),fixedRotation=key==='puma'?[[1,0,0],[0,-1,0],[0,0,-1]]:rotationOnly(model.pose(reference));
  const armFromSlice=(slice)=>{const p0=model.wrist([0,slice[0],slice[1],0,0,0]),q1=-Math.atan2(p0.y,p0.x);return[q1,slice[0],slice[1]];};
  const mapFn=(slice)=>{const p=model.wrist([...armFromSlice(slice),0,0,0]);return[Math.hypot(p.x,p.y),p.z];};
  const numericalDet=(slice)=>{const h=2e-5,f=mapFn(slice),a=mapFn([slice[0]+h,slice[1]]),b=mapFn([slice[0],slice[1]+h]);return((a[0]-f[0])*(b[1]-f[1])-(b[0]-f[0])*(a[1]-f[1]))/(h*h);};
  const pumaFactors=key==='puma'?{
    shoulder:(slice)=>.4318*Math.cos(slice[0])+.0203*Math.sin(slice[0])+.4331*Math.sin(slice[0]+slice[1]),
    elbow:(slice)=>.4318*Math.cos(slice[1])-.0203*Math.sin(slice[1])
  }:null;
  const detFn=pumaFactors?(slice)=>pumaFactors.shoulder(slice)*pumaFactors.elbow(slice):numericalDet;
  state.cache=pumaFactors?buildFactoredMapCache(mapFn,pumaFactors,401):buildNumericalMapCache(mapFn,detFn,241);state.target=mapFn([reference[1],reference[2]]);
  const pair=resizeCanvases([jc,wc],draw);
  function solveTarget(){const armSlices=solveMapIk(state.target,mapFn,detFn).slice(0,4),solutions=[];for(const slice of armSlices){const arm=armFromSlice(slice),wrists=solveWristOrientations(model,arm,fixedRotation).slice(0,2);wrists.forEach(w=>{const q=[...arm,...w];if(!solutions.some(s=>jointDistance(s,q)<3e-2))solutions.push(q);});}state.solutions=solutions;state.selected=0;renderIks();if(solutions.length)viewer.update(solutions[0]);const poseError=solutions.length?Math.max(...solutions.map(q=>rotationMatrixResidual(rotationOnly(model.pose(q)),fixedRotation))):Infinity;status.textContent=`${solutions.length} complete 6R IK solutions · fixed orientation · max R error ${Number.isFinite(poseError)?poseError.toExponential(1):'n/a'} · O_w=(${state.target[0].toFixed(3)}, 0, ${state.target[1].toFixed(3)}) m.`;draw();}
  function renderIks(){const h=host.querySelector('[data-iks]');h.innerHTML=state.solutions.map((q,i)=>`<button data-i="${i}" class="${i===state.selected?'selected':''}" style="border-color:${COLORS[i%COLORS.length]}">IK ${i+1}</button>`).join('');h.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>select(+b.dataset.i)));}
  function select(i){if(!state.solutions.length)return;state.selected=(i+state.solutions.length)%state.solutions.length;viewer.update(state.solutions[state.selected]);renderIks();draw();}
  function draw(){if(!pair.ready()||!state.cache)return;const [a,b]=pair.contexts,[as,bs]=pair.sizes;clear(a,as);clear(b,bs);const jm=plotMap(as,[-PI,PI],[-PI,PI],{x:'q₂',y:'q₃'}),wm=plotMap(bs,state.cache.rhoRange,state.cache.zRange,{x:'ρ',y:'z'});state.jmap=jm;state.wmap=wm;axes(a,jm);axes(b,wm);if(state.cache.factorGroups){state.cache.factorGroups.forEach(group=>{drawSegments(a,group.singularSegments,jm,group.color,2.2);drawSegments(b,group.criticalSegments,wm,group.color,2.2);});drawFactorLegend(a,jm);drawFactorLegend(b,wm);}else{drawSegments(a,state.cache.singularSegments,jm,'#e00000',1.8);drawSegments(b,state.cache.criticalSegments,wm,'#e00000',1.8);}state.solutions.forEach((q,i)=>dot(a,jm.toPx(q[1],q[2]),COLORS[i%COLORS.length],i===state.selected?8:5,'#111'));if(state.target){dot(b,wm.toPx(...state.target),'#fff',7,'#111');ring(b,wm.toPx(...state.target),COLORS[state.selected%COLORS.length],10,3);}}
  wc.addEventListener('pointerdown',(event)=>{const rect=wc.getBoundingClientRect(),p=state.wmap.fromPx(event.clientX-rect.left,event.clientY-rect.top);state.target=[clamp(p[0],state.wmap.xr[0],state.wmap.xr[1]),clamp(p[1],state.wmap.yr[0],state.wmap.yr[1])];status.textContent='Solving arm branches and wrist orientation in the background.';setTimeout(solveTarget,0);});
  const cycle=(time)=>{if(host.querySelector('[data-autoplay]').checked&&state.solutions.length&&time-state.lastCycle>1700){state.lastCycle=time;select(state.selected+1);}requestAnimationFrame(cycle);};requestAnimationFrame(cycle);solveTarget();
}

function buildNumericalMapCache(mapFn,detFn,n){const values=Array.from({length:n},()=>Array(n));let maxR=0,minZ=Infinity,maxZ=-Infinity;for(let i=0;i<n;i+=1)for(let j=0;j<n;j+=1){const q=[-PI+2*PI*i/(n-1),-PI+2*PI*j/(n-1)],w=mapFn(q);values[i][j]=detFn(q);maxR=Math.max(maxR,w[0]);minZ=Math.min(minZ,w[1]);maxZ=Math.max(maxZ,w[1]);}const singularSegments=marchingSquares(values,[-PI,PI],[-PI,PI]),criticalSegments=singularSegments.map(segment=>segment.map(mapFn)),pad=Math.max(.08,(maxZ-minZ)*.08);return{singularSegments,criticalSegments,rhoRange:[0,maxR*1.08],zRange:[minZ-pad,maxZ+pad]};}

function buildFactoredMapCache(mapFn,factors,n){let maxR=0,minZ=Infinity,maxZ=-Infinity;const grids={};for(const name of Object.keys(factors))grids[name]=Array.from({length:n},()=>Array(n));for(let i=0;i<n;i+=1)for(let j=0;j<n;j+=1){const q=[-PI+2*PI*i/(n-1),-PI+2*PI*j/(n-1)],w=mapFn(q);for(const [name,fn] of Object.entries(factors))grids[name][i][j]=fn(q);maxR=Math.max(maxR,w[0]);minZ=Math.min(minZ,w[1]);maxZ=Math.max(maxZ,w[1]);}const palette={shoulder:'#e00000',elbow:'#2474d2'},factorGroups=Object.keys(factors).map(name=>{const singularSegments=marchingSquares(grids[name],[-PI,PI],[-PI,PI]);return{name,color:palette[name],singularSegments,criticalSegments:singularSegments.map(segment=>segment.map(mapFn))};}),pad=Math.max(.08,(maxZ-minZ)*.08);return{factorGroups,rhoRange:[0,maxR*1.08],zRange:[minZ-pad,maxZ+pad]};}

function drawFactorLegend(ctx,map){const entries=[['#e00000','shoulder  fS = 0'],['#2474d2','elbow  a₂c₃ − a₃s₃ = 0']];ctx.save();ctx.font='bold 10px Arial';ctx.textAlign='left';entries.forEach((entry,i)=>{const x=map.pad.l+8+i*112,y=map.pad.t+15;ctx.strokeStyle=entry[0];ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+18,y);ctx.stroke();ctx.fillStyle='#222';ctx.fillText(entry[1],x+23,y+3);});ctx.restore();}

function solveMapIk(target,mapFn,detFn){const roots=[];for(let i=0;i<20;i+=1)for(let j=0;j<20;j+=1){let q=[-PI+2*PI*(i+.31)/20,-PI+2*PI*(j+.67)/20];for(let k=0;k<32;k+=1){const f=mapFn(q),e=[target[0]-f[0],target[1]-f[1]],h=1e-5,a=mapFn([q[0]+h,q[1]]),b=mapFn([q[0],q[1]+h]),J=[[(a[0]-f[0])/h,(b[0]-f[0])/h],[(a[1]-f[1])/h,(b[1]-f[1])/h]],d=J[0][0]*J[1][1]-J[0][1]*J[1][0];if(Math.hypot(...e)<1e-8)break;if(Math.abs(d)<1e-9)break;q=[wrap(q[0]+clamp((e[0]*J[1][1]-J[0][1]*e[1])/d,-.45,.45)),wrap(q[1]+clamp((J[0][0]*e[1]-e[0]*J[1][0])/d,-.45,.45))];}if(distance2(mapFn(q),target)<2e-5&&Math.abs(detFn(q))>1e-5&&!roots.some(r=>torusDistance(r,q)<1.5e-1))roots.push(q);}return roots;}

function solveWristOrientations(model,arm,targetR){const roots=[],values=[-PI,-PI/2,0,PI/2],residual=(w)=>{const R=rotationOnly(model.pose([...arm,...w])),e=[];for(let r=0;r<3;r+=1)for(let c=0;c<3;c+=1)e.push(R[r][c]-targetR[r][c]);return e;};for(const a of values)for(const b of values)for(const c of values){let w=[a,b,c];for(let k=0;k<45;k+=1){const e=residual(w);if(norm(e)<1e-9)break;const h=2e-5,J=Array.from({length:9},()=>Array(3));for(let col=0;col<3;col+=1){const wp=w.slice();wp[col]+=h;const ep=residual(wp);for(let row=0;row<9;row+=1)J[row][col]=(ep[row]-e[row])/h;}const A=Array.from({length:3},(_,r)=>Array.from({length:3},(_,col)=>J.reduce((sum,row)=>sum+row[r]*row[col],r===col?1e-7:0))),bvec=Array.from({length:3},(_,col)=>-J.reduce((sum,row,i)=>sum+row[col]*e[i],0)),step=solveLinear(A,bvec);if(!step.every(Number.isFinite))break;w=w.map((v,i)=>wrap(v+clamp(step[i],-.55,.55)));}const err=norm(residual(w));if(err<2e-6&&!roots.some(r=>jointDistance(r,w)<3e-2))roots.push(w);}for(const w of roots.slice()){const flip=[wrap(w[0]+PI),wrap(-w[1]),wrap(w[2]+PI)];if(norm(residual(flip))<2e-6&&!roots.some(r=>jointDistance(r,flip)<3e-2))roots.push(flip);}return roots;}

function rotationOnly(matrix){const e=matrix.elements;return[[e[0],e[4],e[8]],[e[1],e[5],e[9]],[e[2],e[6],e[10]]];}
function rotationMatrixResidual(a,b){let error=0;for(let r=0;r<3;r+=1)for(let c=0;c<3;c+=1)error=Math.max(error,Math.abs(a[r][c]-b[r][c]));return error;}
function orientationError(current,target){const col=(R,i)=>[R[0][i],R[1][i],R[2][i]],cross3=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],e=[0,0,0];for(let i=0;i<3;i+=1){const c=cross3(col(current,i),col(target,i));for(let k=0;k<3;k+=1)e[k]+=.5*c[k];}return e;}
function norm(v){return Math.hypot(...v);}
function jointDistance(a,b){return Math.hypot(...a.map((v,i)=>wrap(v-b[i])));}

async function createFanuc16Lab(host){host.className+=' cusp-lab cusp-fanuc';host.innerHTML='<div class="cusp-stage" data-stage><div class="hud">custom CRX URDF · uploaded STL · RGB ee frame</div></div><aside class="cusp-fanuc-panel"><div class="cusp-branch-map"><canvas></canvas></div><div class="cusp-iks" data-iks></div><div class="cusp-formula" data-q></div><div class="cusp-status" data-status></div><label class="cusp-toggle"><input type="checkbox" data-autoplay> animate all sixteen IKs</label></aside>';
  const [viewer,response]=await Promise.all([createModelViewer(host.querySelector('[data-stage]'),'fanuc',{embedded:true,showEeFrame:true}),fetch(new URL('../../assets/data/ik16_solutions.csv',import.meta.url))]);if(!response.ok)throw new Error('Could not load ik16_solutions.csv.');const signs=[1,-1,-1,1,-1,-1],offsets=[0,-PI/2,0,PI,PI,0];const rows=(await response.text()).trim().split(/\r?\n/).slice(1).map(line=>{const v=line.split(',').map(Number),qDh=v.slice(1,7).map(x=>x*DEG),q=qDh.map((x,i)=>wrap(signs[i]*x+offsets[i]));return{id:v[0],q,qDh,qDeg:q.map(x=>x/DEG),positionError:v[7],rotationError:v[8],sigma:v[9]};});let selected=0,last=0;const canvas=host.querySelector('.cusp-branch-map canvas'),pair=resizeCanvases([canvas],draw);
  const target=viewer.model.pose(rows[0].q),residuals=rows.map(row=>matrixResidual(viewer.model.pose(row.q),target)),maxResidual=Math.max(...residuals);
  function renderButtons(){const h=host.querySelector('[data-iks]');h.innerHTML=rows.map((r,i)=>`<button data-i="${i}" class="${i===selected?'selected':''}">${r.id}</button>`).join('');h.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>select(+b.dataset.i)));}
  function select(i){selected=(i+rows.length)%rows.length;viewer.update(rows[selected].q);renderButtons();const r=rows[selected];host.querySelector('[data-q]').textContent=`IK ${r.id} · URDF angles\nq = (${r.qDeg.map(x=>`${x.toFixed(2)}°`).join(', ')})`;host.querySelector('[data-status]').textContent=`CSV residuals: position ${r.positionError.toExponential(2)} m · rotation ${r.rotationError.toExponential(2)} rad · scaled σmin ${r.sigma.toFixed(4)}`;draw();}
  function draw(){if(!pair.ready()){const box=canvas.parentElement.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);if(box.width<2||box.height<2)return;canvas.width=Math.round(box.width*dpr);canvas.height=Math.round(box.height*dpr);pair.contexts[0].setTransform(dpr,0,0,dpr,0,0);pair.sizes[0]=[box.width,box.height];}const ctx=pair.contexts[0],size=pair.sizes[0];clear(ctx,size);const map=plotMap(size,[-PI,PI],[-PI,PI],{x:'q₁',y:'q₂'});axes(ctx,map);rows.forEach((r,i)=>dot(ctx,map.toPx(r.q[0],r.q[1]),COLORS[i%COLORS.length],i===selected?8:5,'#111'));}
  const cycle=(time)=>{if(host.querySelector('[data-autoplay]').checked&&time-last>1250){last=time;select(selected+1);}requestAnimationFrame(cycle);};renderButtons();select(0);setTimeout(draw,300);requestAnimationFrame(cycle);console.info(`ENG-654 Lecture 06 FANUC CSV check: ${rows.length} solutions loaded, maximum URDF FK matrix residual ${maxResidual}.`);}

function matrixResidual(a,b){return Math.max(...a.elements.map((v,i)=>Math.abs(v-b.elements[i])));}

function buildSingularityCache(p,n=321) {
  const values=Array.from({length:n},()=>Array(n));let maxR=0,minZ=Infinity,maxZ=-Infinity;
  for(let i=0;i<n;i+=1)for(let j=0;j<n;j+=1){const q2=-PI+2*PI*i/(n-1),q3=-PI+2*PI*j/(n-1);values[i][j]=det3([0,q2,q3],p);const w=sliceFk([q2,q3],p);maxR=Math.max(maxR,w[0]);minZ=Math.min(minZ,w[1]);maxZ=Math.max(maxZ,w[1]);}
  const singularSegments=marchingSquares(values,[-PI,PI],[-PI,PI]),criticalBranches=algebraicCriticalBranches(p,1000);
  const padZ=Math.max(.4,(maxZ-minZ)*.08);return{singularSegments,criticalBranches,rhoRange:[0,maxR*1.08],zRange:[minZ-padZ,maxZ+padZ]};
}

function marchingSquares(values,xr,yr){const nx=values.length,ny=values[0].length,segments=[],point=(i,j)=>[xr[0]+(xr[1]-xr[0])*i/(nx-1),yr[0]+(yr[1]-yr[0])*j/(ny-1)],cross=(p0,p1,v0,v1)=>{const t=v0===v1?.5:v0/(v0-v1);return[p0[0]+t*(p1[0]-p0[0]),p0[1]+t*(p1[1]-p0[1])];};for(let i=0;i<nx-1;i+=1)for(let j=0;j<ny-1;j+=1){const p=[point(i,j),point(i+1,j),point(i+1,j+1),point(i,j+1)],v=[values[i][j],values[i+1][j],values[i+1][j+1],values[i][j+1]],hits=[];for(let e=0;e<4;e+=1){const k=(e+1)%4;if((v[e]<=0&&v[k]>0)||(v[e]>0&&v[k]<=0))hits.push(cross(p[e],p[k],v[e],v[k]));}if(hits.length===2)segments.push(hits);else if(hits.length===4){const center=(v[0]+v[1]+v[2]+v[3])/4;if((v[0]>0)=== (center>0))segments.push([hits[0],hits[3]],[hits[1],hits[2]]);else segments.push([hits[0],hits[1]],[hits[2],hits[3]]);}}return segments;}

function algebraicCriticalBranches(p,count){const branches=[],active=[];for(let i=0;i<count;i+=1){const q2=-PI+2*PI*i/(count-1),coeff=detPolynomialV(q2,p),roots=realPolynomialRoots(coeff).map(v=>2*Math.atan(v)).sort((a,b)=>a-b),used=new Set();for(let k=0;k<active.length;k+=1){let best=-1,dist=.22;for(let r=0;r<roots.length;r+=1)if(!used.has(r)&&Math.abs(wrap(roots[r]-active[k].q3))<dist){best=r;dist=Math.abs(wrap(roots[r]-active[k].q3));}if(best>=0){active[k].q3=roots[best];active[k].points.push(sliceFk([q2,roots[best]],p));used.add(best);}else{if(active[k].points.length>1)branches.push(active[k].points);active[k].points=[];}}for(let r=0;r<roots.length;r+=1)if(!used.has(r))active.push({q3:roots[r],points:[sliceFk([q2,roots[r]],p)]});}
  active.forEach(a=>{if(a.points.length>1)branches.push(a.points);});if(p.a1<1e-7&&close(p.A1,PI/2)&&close(p.A2,PI/2)){for(const q2 of [-PI/2,PI/2])branches.push(Array.from({length:1000},(_,i)=>sliceFk([q2,-PI+2*PI*i/999],p)));}return branches;}

function detPolynomialV(q2,p){const samples=[-2,-1,0,1,2],A=samples.map(v=>[1,v,v*v,v**3,v**4]),b=samples.map(v=>det3([0,q2,2*Math.atan(v)],p)*(1+v*v)**2);return solveLinear(A,b);}
function realPolynomialRoots(coeff){let c=coeff.slice();while(c.length>1&&Math.abs(c.at(-1))<1e-8)c.pop();const degree=c.length-1;if(degree<1)return[];if(degree===1)return[-c[0]/c[1]];const derivative=c.slice(1).map((v,i)=>v*(i+1)),critical=realPolynomialRoots(derivative).sort((a,b)=>a-b),bound=1+Math.max(...c.slice(0,-1).map(v=>Math.abs(v/c.at(-1)))),cuts=[-bound,...critical.filter(x=>x>-bound&&x<bound),bound],evalP=(x)=>c.reduceRight((s,v)=>s*x+v,0),roots=[];for(const x of critical)if(Math.abs(evalP(x))<1e-6)roots.push(x);for(let i=0;i<cuts.length-1;i+=1){let a=cuts[i],b=cuts[i+1],fa=evalP(a),fb=evalP(b);if(fa===0)roots.push(a);if(fa*fb>0)continue;for(let k=0;k<60;k+=1){const m=(a+b)/2,fm=evalP(m);if(fa*fm<=0){b=m;fb=fm;}else{a=m;fa=fm;}}roots.push((a+b)/2);}return roots.filter(Number.isFinite).sort((a,b)=>a-b).filter((x,i,a)=>i===0||Math.abs(x-a[i-1])>1e-5);}

function solveIkSlice(target,p) {
  const roots=[];
  for(let i=0;i<18;i+=1)for(let j=0;j<18;j+=1){let q=[-PI+2*PI*(i+.35)/18,-PI+2*PI*(j+.65)/18];for(let k=0;k<35;k+=1){const f=sliceFk(q,p),e=[target[0]-f[0],target[1]-f[1]];if(Math.hypot(...e)<1e-8)break;const h=1e-5,fx=sliceFk([q[0]+h,q[1]],p),fy=sliceFk([q[0],q[1]+h],p),J=[[(fx[0]-f[0])/h,(fy[0]-f[0])/h],[(fx[1]-f[1])/h,(fy[1]-f[1])/h]],d=J[0][0]*J[1][1]-J[0][1]*J[1][0];if(Math.abs(d)<1e-9)break;const dq=[(e[0]*J[1][1]-J[0][1]*e[1])/d,(J[0][0]*e[1]-e[0]*J[1][0])/d];q=[wrap(q[0]+clamp(dq[0],-.5,.5)),wrap(q[1]+clamp(dq[1],-.5,.5))];}
    if(distance2(sliceFk(q,p),target)<1e-6&&Math.abs(det3([0,...q],p))>1e-5&&!roots.some(r=>torusDistance(r,q)<2e-3))roots.push(q);
  }
  return roots.sort((a,b)=>a[0]-b[0]||a[1]-b[1]);
}

function planAspectPath(a,b,p) {
  const direct=Array.from({length:61},(_,i)=>[angleLerp(a[0],b[0],i/60),angleLerp(a[1],b[1],i/60)]),scale=Math.max(1,Math.abs(det3([0,...a],p))),margin=.012*scale;
  if(direct.every(q=>Math.abs(det3([0,...q],p))>margin))return direct;
  const n=100,toIndex=(q)=>q.map(x=>Math.round((wrap(x)+PI)/(2*PI)*(n-1))%(n-1)),start=toIndex(a),goal=toIndex(b),key=(i,j)=>`${i},${j}`,sign=Math.sign(det3([0,...a],p)),open=[[0,start[0],start[1]]],came=new Map(),cost=new Map([[key(...start),0]]),neighbors=[[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]];
  let found=null,guard=0;while(open.length&&guard<26000){guard+=1;open.sort((x,y)=>x[0]-y[0]);const [,i,j]=open.shift(),k=key(i,j);if(i===goal[0]&&j===goal[1]){found=[i,j];break;}for(const [di,dj] of neighbors){const ni=(i+di+n-1)%(n-1),nj=(j+dj+n-1)%(n-1),q=[-PI+2*PI*ni/(n-1),-PI+2*PI*nj/(n-1)],d=det3([0,...q],p);if(Math.sign(d)!==sign||Math.abs(d)<margin)continue;const nk=key(ni,nj),g=cost.get(k)+Math.hypot(di,dj);if(g>=(cost.get(nk)??Infinity))continue;cost.set(nk,g);came.set(nk,[i,j]);const hx=Math.min(Math.abs(ni-goal[0]),n-1-Math.abs(ni-goal[0])),hy=Math.min(Math.abs(nj-goal[1]),n-1-Math.abs(nj-goal[1]));open.push([g+Math.hypot(hx,hy),ni,nj]);}}
  if(!found)return[];const cells=[];for(let c=found;c;){cells.push(c);const prev=came.get(key(...c));if(!prev)break;c=prev;}cells.reverse();let path=cells.map(([i,j])=>[-PI+2*PI*i/(n-1),-PI+2*PI*j/(n-1)]);path[0]=a;path[path.length-1]=b;path=simplifyPath(path,p,margin);return path;
}

function simplifyPath(path,p,margin){const out=[path[0]];let i=0;while(i<path.length-1){let best=i+1;for(let j=path.length-1;j>i+1;j-=1){let safe=true;for(let k=1;k<18;k+=1){const q=[angleLerp(path[i][0],path[j][0],k/18),angleLerp(path[i][1],path[j][1],k/18)];if(Math.abs(det3([0,...q],p))<margin){safe=false;break;}}if(safe){best=j;break;}}out.push(path[best]);i=best;}const dense=[];for(let k=0;k<out.length-1;k+=1)for(let s=0;s<20;s+=1)dense.push([angleLerp(out[k][0],out[k+1][0],s/20),angleLerp(out[k][1],out[k+1][1],s/20)]);dense.push(out.at(-1));return dense;}

function verifyContinuation(path,p){let seed=path[0].slice();for(let i=1;i<path.length;i+=Math.max(1,Math.floor(path.length/40))){const target=sliceFk(path[i],p),sol=solveNear(target,seed,p);if(!sol||torusDistance(sol,path[i])>.08)return false;seed=sol;}return true;}
async function verifyFullIkContinuation(path,viewer,solvePosition){if(!path.length)return false;const stride=Math.max(1,Math.floor(path.length/14));for(let i=0;i<path.length;i+=stride){const q=path[i],point=viewer.point(q),solutions=await solvePosition([point.x,point.y,point.z]);if(!solutions.some(candidate=>Math.hypot(...candidate.map((angle,j)=>wrap(angle-q[j])))<2e-3))return false;}const q=path.at(-1),point=viewer.point(q),solutions=await solvePosition([point.x,point.y,point.z]);return solutions.some(candidate=>Math.hypot(...candidate.map((angle,j)=>wrap(angle-q[j])))<2e-3);}
function solveNear(target,seed,p){let q=seed.slice();for(let k=0;k<18;k+=1){const f=sliceFk(q,p),e=[target[0]-f[0],target[1]-f[1]],h=1e-5,fx=sliceFk([q[0]+h,q[1]],p),fy=sliceFk([q[0],q[1]+h],p),a=(fx[0]-f[0])/h,b=(fy[0]-f[0])/h,c=(fx[1]-f[1])/h,d=(fy[1]-f[1])/h,det=a*d-b*c;if(Math.abs(det)<1e-9)return null;q=[wrap(q[0]+clamp((e[0]*d-b*e[1])/det,-.3,.3)),wrap(q[1]+clamp((a*e[1]-e[0]*c)/det,-.3,.3))];if(Math.hypot(...e)<1e-7)return q;}return distance2(sliceFk(q,p),target)<1e-5?q:null;}

function sliceFk(q,p){const v=fkDh([0,q[0],q[1]],p).end;return[Math.hypot(v.x,v.y),v.z];}
function det3(q,p){const k=fkDh(q,p),cols=k.axes.map((z,i)=>z.clone().cross(k.end.clone().sub(k.origins[i])));return cols[0].dot(cols[1].clone().cross(cols[2]));}
function fkDh(q,p){const rows=[[p.a1,p.A1,p.d1],[p.a2,p.A2,p.d2],[p.a3,p.A3,p.d3]],T=new THREE.Matrix4(),origins=[],axes=[];for(let i=0;i<3;i+=1){origins.push(new THREE.Vector3().setFromMatrixPosition(T));axes.push(new THREE.Vector3(0,0,1).transformDirection(T));T.multiply(dhMatrix(q[i],...rows[i]));}return{end:new THREE.Vector3().setFromMatrixPosition(T),origins,axes,T};}
function dhMatrix(theta,a,alpha,d){const c=Math.cos(theta),s=Math.sin(theta),ca=Math.cos(alpha),sa=Math.sin(alpha);return new THREE.Matrix4().set(c,-s*ca,s*sa,a*c,s,c*ca,-c*sa,a*s,0,sa,ca,d,0,0,0,1);}

function factorText(p){
  if(close(p.A1,PI/2)&&close(p.A2,PI/2)&&close(p.d2,1)&&close(p.d3,0)&&close(p.a2,2)&&close(p.a3,1.5))return p.a1<.05?'det(Jₚ) = ¾(3c₃ + 4)c₂(c₃ − 2s₃)\nindependent of q₁, d₁, α₃':'det(Jₚ) = ¾(3c₃ + 4)[c₂(c₃ − 2s₃) − s₃]\nindependent of q₁, d₁, α₃';
  const [[a1,A1],[a2,A2,d2],[a3,,d3]]=[[p.a1,p.A1,p.d1],[p.a2,p.A2,p.d2],[p.a3,p.A3,p.d3]],s1=Math.sin(A1),c1=Math.cos(A1),s2=Math.sin(A2),c2=Math.cos(A2),terms=(xs)=>xs.filter(([v])=>Math.abs(v)>1e-7).map(([v,t],i)=>`${i?(v>=0?' + ':' − '):(v<0?'−':'')}${Math.abs(v).toFixed(3)}${t}`).join('')||'0';
  const f0=terms([[-a1*a2*s1,'s₃'],[-a1*a3*s1*s2*s2,'s₃c₃'],[-a1*d3*s1*s2*c2,'c₃']]),fs=terms([[a1*a2*s2*c1+d2*d3*s1*s2*s2,'c₃'],[a1*a3*s2*c1,'c₃²'],[a2*a3*s1*c2,'s₃²'],[-a2*d3*s1*s2,'s₃'],[-a3*d2*s1*s2*c2,'s₃c₃']]),fc=terms([[a1*a3*s2*c1*c2-a2*a3*s1,'s₃c₃'],[-a1*d3*s2*s2*c1+a2*d2*s1*s2,'c₃'],[-a2*a2*s1,'s₃'],[a3*d2*s1*s2,'c₃²']]);return`det(Jₚ) = ${a3.toFixed(3)}[F₀ + s₂Fₛ + c₂F꜀]\nF₀ = ${f0}\nFₛ = ${fs}\nF꜀ = ${fc}\nindependent of q₁, d₁, α₃`;
}

export async function createModelViewer(host,key,options={}) {
  const spec=MODEL_SPECS[key],kit=createThreeKit(host,spec),model=await loadUrdfRobot(kit.world,spec);let q=spec.q.map(v=>v*DEG),ghost=null,trace=null,eeFrame=null;if(options.showEeFrame){eeFrame=new THREE.Group();const axes=new THREE.AxesHelper(spec.frameScale||.25),origin=new THREE.Mesh(new THREE.SphereGeometry((spec.frameScale||.25)*.055,16,10),new THREE.MeshBasicMaterial({color:0x111111}));eeFrame.add(axes,origin);eeFrame.matrixAutoUpdate=false;eeFrame.renderOrder=15;kit.world.add(eeFrame);}const updateFrame=(next)=>{if(eeFrame){eeFrame.matrix.copy(model.pose(next));eeFrame.matrixWorldNeedsUpdate=true;}};model.update(q);updateFrame(q);kit.render();
  if(!options.embedded&&!host.hasAttribute('data-hide-badge')){const badge=document.createElement('div');badge.className='hud';badge.textContent=`${model.meshCount} uploaded STL links`;host.classList.add('cusp-stage');host.append(badge);}
  return {update(next){q=next.slice();model.update(q);updateFrame(q);kit.render();},point(next){return model.point(next);},sliceConfiguration(slice){const p0=model.point([0,slice[0],slice[1]]);return[-Math.atan2(p0.y,p0.x),slice[0],slice[1]];},setGhost(next){ghost?.removeFromParent();ghost=model.root.clone(true);ghost.traverse(o=>{if(o.isMesh){o.material=o.material.clone();o.material.transparent=true;o.material.opacity=.18;o.material.depthWrite=false;}});kit.world.add(ghost);model.applyTo(ghost,next);kit.render();},setTrace(points){trace?.removeFromParent();if(points.length>1){const g=new THREE.BufferGeometry().setFromPoints(points),m=new THREE.LineBasicMaterial({color:0x2474d2,linewidth:3});trace=new THREE.Line(g,m);kit.world.add(trace);}kit.render();},model,dispose:kit.dispose};
}

function createThreeKit(host,spec){const scene=new THREE.Scene();scene.background=new THREE.Color(0xf3f4f5);const camera=new THREE.PerspectiveCamera(38,1,.01,100);camera.position.fromArray(spec.camera);const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.7));renderer.outputColorSpace=THREE.SRGBColorSpace;host.prepend(renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x5b6670,2.5));const light=new THREE.DirectionalLight(0xffffff,2.5);light.position.set(6,9,10);scene.add(light);const world=createZUpWorld(scene),grid=new THREE.GridHelper(12,24,0xc3c7cb,0xe3e5e7);grid.rotation.x=PI/2;world.add(grid);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(spec.target[0],spec.target[2],-spec.target[1]);controls.enableDamping=true;controls.update();let raf=0,dirty=true;const frame=()=>{raf=0;if(!dirty)return;dirty=false;controls.update();renderer.render(scene,camera);};const render=()=>{dirty=true;if(!raf)raf=requestAnimationFrame(frame);};controls.addEventListener('change',render);const ro=new ResizeObserver(()=>{resizeRendererToContainer(renderer,camera,host);render();});ro.observe(host);resizeRendererToContainer(renderer,camera,host);render();return{scene,camera,renderer,world,controls,render,dispose(){ro.disconnect();controls.dispose();renderer.dispose();cancelAnimationFrame(raf);}};}

async function loadUrdfRobot(world,spec){const urdfUrl=versionedAssetUrl(spec.urdf),response=await fetch(urdfUrl);if(!response.ok)throw new Error(`Could not load ${urdfUrl.pathname.split('/').at(-1)}.`);const xml=new DOMParser().parseFromString(await response.text(),'application/xml'),links=new Map(),joints=[];for(const el of xml.querySelectorAll('link'))links.set(el.getAttribute('name'),{name:el.getAttribute('name'),visual:parseVisual(el)});for(const el of xml.querySelectorAll('joint')){const direct=(tag)=>[...el.children].find(x=>x.tagName.toLowerCase()===tag),origin=parseOrigin(direct('origin')),axis=parseVec(direct('axis')?.getAttribute('xyz')||'0 0 1');joints.push({name:el.getAttribute('name'),type:el.getAttribute('type'),parent:direct('parent')?.getAttribute('link'),child:direct('child')?.getAttribute('link'),origin,axis:new THREE.Vector3(...axis).normalize()});}const childNames=new Set(joints.map(j=>j.child)),rootName=[...links.keys()].find(x=>!childNames.has(x)),root=new THREE.Group(),movable=[],nodeByLink=new Map();world.add(root);let meshCount=0;
  async function build(linkName,parent){const link=links.get(linkName),node=new THREE.Group();node.userData.linkName=linkName;parent.add(node);nodeByLink.set(linkName,node);if(link?.visual){const holder=new THREE.Group();holder.applyMatrix4(link.visual.origin);const file=link.visual.file.split('/').at(-1),meshUrl=versionedAssetUrl(file,new URL(spec.mesh,import.meta.url)),r=await fetch(meshUrl);if(!r.ok)throw new Error(`Could not load uploaded STL ${file}.`);const geom=parseStlGeometry(await r.arrayBuffer()),mat=new THREE.MeshStandardMaterial({color:meshColor(meshCount),roughness:.62,metalness:.06});const mesh=new THREE.Mesh(geom,mat);mesh.scale.fromArray(link.visual.scale);holder.add(mesh);node.add(holder);meshCount+=1;}for(const joint of joints.filter(j=>j.parent===linkName)){const originNode=new THREE.Group();originNode.applyMatrix4(joint.origin);node.add(originNode);const rotor=new THREE.Group();originNode.add(rotor);joint.rotor=rotor;if(joint.type!=='fixed')movable.push(joint);await build(joint.child,rotor);}}
  await build(rootName,root);const update=(q,target=root)=>{target.traverse(o=>{if(o.userData.jointIndex!=null){const joint=movable[o.userData.jointIndex],angle=q[o.userData.jointIndex]||0;o.quaternion.setFromAxisAngle(joint.axis,angle);}});};movable.forEach((joint,i)=>{joint.rotor.userData.jointIndex=i;joint.movableIndex=i;});
  const findPath=(linkName,target,path=[])=>{if(linkName===target)return path;for(const joint of joints.filter(j=>j.parent===linkName)){const found=findPath(joint.child,target,[...path,joint]);if(found)return found;}return null;},serial=findPath(rootName,spec.end)||[];
  const pose=(q)=>{const T=new THREE.Matrix4();for(const joint of serial){T.multiply(joint.origin);if(joint.type!=='fixed')T.multiply(new THREE.Matrix4().makeRotationAxis(joint.axis,q[joint.movableIndex]||0));}return T;};
  const geometricJacobian=(q)=>{const T=new THREE.Matrix4(),origins=[],axes=[],indices=[];for(const joint of serial){T.multiply(joint.origin);if(joint.type!=='fixed'){origins.push(new THREE.Vector3().setFromMatrixPosition(T));axes.push(joint.axis.clone().transformDirection(T));indices.push(joint.movableIndex);T.multiply(new THREE.Matrix4().makeRotationAxis(joint.axis,q[joint.movableIndex]||0));}}const p=new THREE.Vector3().setFromMatrixPosition(T),columns=origins.map((o,i)=>{const v=axes[i].clone().cross(p.clone().sub(o));return[v.x,v.y,v.z,axes[i].x,axes[i].y,axes[i].z];});return{columns,indices,p,T};};
  const wrist=(q)=>{const T=new THREE.Matrix4();let count=0;for(const joint of serial){T.multiply(joint.origin);if(joint.type!=='fixed'){if(count===4)return new THREE.Vector3().setFromMatrixPosition(T);T.multiply(new THREE.Matrix4().makeRotationAxis(joint.axis,q[joint.movableIndex]||0));count+=1;}}return new THREE.Vector3().setFromMatrixPosition(T);};
  const applyTo=(clone,q)=>{clone.traverse(o=>{if(o.userData.jointIndex!=null){const i=o.userData.jointIndex;o.quaternion.setFromAxisAngle(movable[i].axis,q[i]||0);}});};const point=(q,linkName=spec.end)=>{update(q);root.updateMatrixWorld(true);const node=nodeByLink.get(linkName);if(!node)return new THREE.Vector3();const value=node.getWorldPosition(new THREE.Vector3());return root.worldToLocal(value);};return{root,movable,meshCount,update,applyTo,point,pose,geometricJacobian,wrist,nodeByLink};}

function parseVisual(link){const visual=[...link.children].find(x=>x.tagName.toLowerCase()==='visual');if(!visual)return null;const mesh=visual.querySelector('geometry > mesh');if(!mesh)return null;return{file:mesh.getAttribute('filename'),scale:parseVec(mesh.getAttribute('scale')||'1 1 1'),origin:parseOrigin([...visual.children].find(x=>x.tagName.toLowerCase()==='origin'))};}
function versionedAssetUrl(path,base=import.meta.url){const url=new URL(path,base);url.searchParams.set('v',MODULE_REVISION);return url;}
function parseOrigin(el){const xyz=parseVec(el?.getAttribute('xyz')||'0 0 0'),rpy=parseVec(el?.getAttribute('rpy')||'0 0 0'),r=new THREE.Matrix4().makeRotationZ(rpy[2]).multiply(new THREE.Matrix4().makeRotationY(rpy[1])).multiply(new THREE.Matrix4().makeRotationX(rpy[0]));return new THREE.Matrix4().makeTranslation(...xyz).multiply(r);}
function parseVec(s){return s.trim().split(/\s+/).map(Number);}
function meshColor(i){return[0x333638,0x0d7d80,0xb8b8b8,0x0d7d80,0x90959a,0x0d7d80,0x666b70][i%7];}

function resizeCanvases(canvases,onResize){const contexts=canvases.map(c=>c.getContext('2d')),sizes=canvases.map(()=>[0,0]);const ro=new ResizeObserver(()=>{canvases.forEach((c,i)=>{const dpr=Math.min(devicePixelRatio||1,2),w=Math.max(1,c.clientWidth),h=Math.max(1,c.clientHeight);if(c.width!==Math.round(w*dpr)||c.height!==Math.round(h*dpr)){c.width=Math.round(w*dpr);c.height=Math.round(h*dpr);contexts[i].setTransform(dpr,0,0,dpr,0,0);sizes[i]=[w,h];}});onResize();});canvases.forEach(c=>ro.observe(c));return{contexts,sizes,ready:()=>sizes.every(s=>s[0]>1&&s[1]>1),ro};}
function plotMap(size,xr,yr,labels={}){const pad={l:42,r:12,t:27,b:32},w=Math.max(1,size[0]-pad.l-pad.r),h=Math.max(1,size[1]-pad.t-pad.b),toPx=(x,y)=>[pad.l+(x-xr[0])/(xr[1]-xr[0])*w,pad.t+(yr[1]-y)/(yr[1]-yr[0])*h],fromPx=(x,y)=>[xr[0]+(x-pad.l)/w*(xr[1]-xr[0]),yr[1]-(y-pad.t)/h*(yr[1]-yr[0])];return{size,xr,yr,pad,w,h,toPx,fromPx,labels};}
function axes(ctx,m){ctx.save();ctx.strokeStyle='#aaa';ctx.lineWidth=1;ctx.strokeRect(m.pad.l,m.pad.t,m.w,m.h);ctx.fillStyle='#333';ctx.font='12px Arial';ctx.textAlign='center';ctx.fillText(m.labels.x||'',m.pad.l+m.w/2,m.size[1]-7);ctx.save();ctx.translate(12,m.pad.t+m.h/2);ctx.rotate(-PI/2);ctx.fillText(m.labels.y||'',0,0);ctx.restore();ctx.font='10px Arial';ctx.textAlign='left';ctx.fillText(formatTick(m.xr[0]),m.pad.l,m.size[1]-18);ctx.textAlign='right';ctx.fillText(formatTick(m.xr[1]),m.pad.l+m.w,m.size[1]-18);ctx.textAlign='right';ctx.fillText(formatTick(m.yr[1]),m.pad.l-5,m.pad.t+4);ctx.fillText(formatTick(m.yr[0]),m.pad.l-5,m.pad.t+m.h);ctx.restore();}
function fillPlot(ctx,m,xr,yr,color){const a=m.toPx(xr[0],yr[1]),b=m.toPx(xr[1],yr[0]);ctx.fillStyle=color;ctx.fillRect(a[0],a[1],b[0]-a[0],b[1]-a[1]);}
function scatter(ctx,pts,m,color,r=1.5){ctx.fillStyle=color;for(const p of pts){const q=m.toPx(...p);ctx.fillRect(q[0]-r,q[1]-r,2*r,2*r);}}
function drawSegments(ctx,segments,m,color,width=2){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();for(const segment of segments){const a=m.toPx(...segment[0]),b=m.toPx(...segment[1]);ctx.moveTo(...a);ctx.lineTo(...b);}ctx.stroke();}
function polyline(ctx,pts,m,color,width=2){polylinePx(ctx,pts.map(p=>m.toPx(...p)),color,width);}
function polylineTorus(ctx,pts,m,color,width=2){if(!pts.length)return;let segment=[pts[0]];for(let i=1;i<pts.length;i+=1){if(Math.abs(pts[i][0]-pts[i-1][0])>PI||Math.abs(pts[i][1]-pts[i-1][1])>PI){if(segment.length>1)polyline(ctx,segment,m,color,width);segment=[pts[i]];}else segment.push(pts[i]);}if(segment.length>1)polyline(ctx,segment,m,color,width);}
function polylinePx(ctx,pts,color,width=2){if(!pts.length)return;ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineJoin='round';ctx.lineCap='round';ctx.beginPath();ctx.moveTo(...pts[0]);for(let i=1;i<pts.length;i+=1)ctx.lineTo(...pts[i]);ctx.stroke();}
function circlePlot(ctx,m,r,color,width){const pts=Array.from({length:121},(_,i)=>[r*Math.cos(2*PI*i/120),r*Math.sin(2*PI*i/120)]);polyline(ctx,pts,m,color,width);}
function dot(ctx,p,color,r=6,stroke){ctx.beginPath();ctx.arc(p[0],p[1],r,0,2*PI);ctx.fillStyle=color;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.stroke();}}
function ring(ctx,p,color,r=7,width=2){ctx.beginPath();ctx.arc(p[0],p[1],r,0,2*PI);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();}
function clear(ctx,size){ctx.clearRect(0,0,size[0],size[1]);ctx.fillStyle='#fff';ctx.fillRect(0,0,size[0],size[1]);}
function bindDrag(canvas,onPoint,getMap){let active=false;const act=(e)=>{const r=canvas.getBoundingClientRect(),m=getMap(),p=m.fromPx(e.clientX-r.left,e.clientY-r.top);onPoint(clamp(p[0],m.xr[0],m.xr[1]),clamp(p[1],m.yr[0],m.yr[1]));};canvas.addEventListener('pointerdown',(e)=>{active=true;canvas.setPointerCapture(e.pointerId);act(e);});canvas.addEventListener('pointermove',(e)=>{if(active)act(e);});canvas.addEventListener('pointerup',()=>active=false);}
function addRange(host,label,min,max,step,value,onInput,suffix='°'){const row=document.createElement('label');row.className='cusp-range';row.innerHTML=`<span>${label}</span><input type="range" min="${min}" max="${max}" step="${step}" value="${value}"><output>${Number(value).toFixed(step<1?2:0)}${suffix}</output>`;const input=row.querySelector('input'),out=row.querySelector('output');input.addEventListener('input',()=>{out.textContent=`${Number(input.value).toFixed(step<1?2:0)}${suffix}`;onInput(Number(input.value));});host.append(row);return input;}
function syncRanges(host,values){host.querySelectorAll('input[type=range]').forEach((input,i)=>{input.value=values[i];input.nextElementSibling.textContent=`${Number(values[i]).toFixed(i>1?2:0)}${i>1?' m':'°'}`;});}
function angleLerp(a,b,t){return wrap(a+wrap(b-a)*t);}
function wrap(x){while(x>PI)x-=2*PI;while(x<=-PI)x+=2*PI;return x;}
function torusDistance(a,b){return Math.hypot(wrap(a[0]-b[0]),wrap(a[1]-b[1]));}
function distance2(a,b){return Math.hypot(a[0]-b[0],a[1]-b[1]);}
function solveLinear(A,b){const M=A.map((row,i)=>[...row,b[i]]),n=b.length;for(let i=0;i<n;i+=1){let pivot=i;for(let r=i+1;r<n;r+=1)if(Math.abs(M[r][i])>Math.abs(M[pivot][i]))pivot=r;if(Math.abs(M[pivot][i])<1e-12)return Array(n).fill(NaN);[M[i],M[pivot]]=[M[pivot],M[i]];const d=M[i][i];for(let c=i;c<=n;c+=1)M[i][c]/=d;for(let r=0;r<n;r+=1)if(r!==i){const f=M[r][i];for(let c=i;c<=n;c+=1)M[r][c]-=f*M[i][c];}}return M.map(row=>row[n]);}
function clamp(x,a,b){return Math.max(a,Math.min(b,x));}
function close(a,b,t=1e-8){return Math.abs(a-b)<t;}
function formatTick(x){if(close(x,PI))return'π';if(close(x,-PI))return'−π';return Number(x).toFixed(1);}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}

function runChecks(){try{for(const name of Object.keys(PRESETS)){const p=PRESETS[name];for(let i=0;i<10;i+=1){const q=[0,(Math.random()*2-1)*PI,(Math.random()*2-1)*PI],direct=det3(q,p),s2=Math.sin(q[1]),c2=Math.cos(q[1]),s3=Math.sin(q[2]),c3=Math.cos(q[2]),expected=.75*(3*c3+4)*(p.a1===0?c2*(c3-2*s3):c2*(c3-2*s3)-s3);if(Math.abs(direct-expected)>1e-8*Math.max(1,Math.abs(direct)))throw new Error(`${name} determinant check failed`);}}console.info('ENG-654 Lecture 06 checks passed: both uploaded 3R determinant presets agree with direct D-H Jacobians.');}catch(error){console.error('ENG-654 Lecture 06 validation failed:',error);}}
